### ISSUE TITLE
Exported DAE with a very basic skeletal animation is completely broken, but works fine in 'Better Collada' exporter

### ISSUE THREAD

**Issue by chuckhacker** [gregeryb/DAEBlend#5]
This low poly Blender3D model with a skeletal walking animation is completely broken when exporting to DAE with DAEBlend. However, it works perfectly fine in 'Better Collada' exporter:

You can see a MKV video of the resultant broken animation in the DAE file generated by your exporter here in my attached ZIP file, along with everything you need to repro this issue -- original example problematic .blend model used, PNG texture for said model, DAE output file:
 
[broken_dae.zip](https://github.com/gregeryb/DAEBlend/files/1082913/broken_dae.zip)

We are experiencing this issue with Blender version 2.78c (but we expect it to be a problem with other versions as well).

What draws me to your exporter over Better Collada is that yours ostensibly supports multiple animations per file, whereas Better Collada does not.

Hope that helps, thanks!

**Comment by gregdavisd** [comment]
Hello Chuck,
I've been trying to reproduce the problem and found a few issues:

- Setting 'Apply Modifiers' will alter the rest mesh to a pose mesh, where the skeletal animations expects a true rest pose as a starting position. The quick fix here is to not use 'Apply Modifiers' when exporting an armature until this is properly fixed.

- Better Collada seems to normalize vertex weights whereas DAEBlend doesn't. There was a few vertices on the feet and legs that have a total weight over 1.0. Using the 'Tools->Weight Tools->Normalize All' fixed this. Normalizing should probably be added to DAEBlend as well.

- DAEBlend adds the bones listed in the mesh 'Vertex Groups' to the skin controller which may not be every bone in the skeleton. There is 18bones listed under the mesh 'Vertex Groups'. Better Collada added all 22 bones from the armature into the skin controller with 4 being unused. To get this behavior in DAEBlend you could add the extra unused bones to the vertex groups. To handle this correctly in an animation system the bones should be initialized with the \<matrix\> value under the bone's \<node\> tag in case the skin controller doesn't target them.

I tested the animation using ASSIMP 3.3.1 viewer. I had to remove the material texture because Assimp gave an error about the texture URL, probably an incompatibility with Assimp. Here is the animation in Assimp viewer after deleting the texture,normalizing the vertex weights and exporting with DAEBlend:

https://www.youtube.com/watch?v=LlxrGeoxeLk

Hope that helps.

**Comment by gregdavisd** [comment]
I've uploaded changes to add a drop down box to select Three.js compatibility. 

To default to three.js compatibility you can change line 148 of __init__.py to:       default='THREE',

that way it won't have to be set every time in blender.

[yeti-compat-fix.zip](https://github.com/gregeryb/DAEBlend/files/1083367/yeti-compat-fix.zip)
Regards,
Greg.
